from pathlib import Path
from datetime import datetime
import random

DESIGN_DIR = Path(__file__).parent.parent / "designs"
OUTPUT = DESIGN_DIR / "game-design.md"

GAME_IDEAS = [
    {
        "title": "Gravity Flip",
        "description": "A fast arcade game where the player flips gravity to avoid obstacles.",
        "objective": "Reach the finish while surviving the obstacle field.",
        "controls": "Press Space to flip gravity.",
        "mechanic": "The player alternates between floor and ceiling movement.",
        "win": "Reach the finish zone.",
        "lose": "Hit an obstacle or leave the playable area.",
        "hazards": "Moving spikes and barriers.",
        "targets": "Finish portal.",
    },
    {
        "title": "Orb Runner",
        "description": "A reflex game where the player collects glowing orbs while avoiding hunters.",
        "objective": "Collect enough orbs before losing all lives.",
        "controls": "Use Arrow Keys or WASD to move.",
        "mechanic": "Collect orbs while avoiding moving enemies.",
        "win": "Collect 10 orbs.",
        "lose": "Lose all three lives.",
        "hazards": "Chasing enemy drones.",
        "targets": "Glowing collectible orbs.",
    },
    {
        "title": "Laser Dodge",
        "description": "An arcade survival game where the player dodges sweeping laser beams.",
        "objective": "Survive long enough to reach the extraction timer.",
        "controls": "Use Arrow Keys or WASD to move.",
        "mechanic": "Predict and dodge rotating laser beams.",
        "win": "Survive for 30 seconds.",
        "lose": "Touch a laser beam.",
        "hazards": "Rotating laser beams.",
        "targets": "Extraction zone.",
    },
    {
        "title": "Color Gate",
        "description": "A reaction puzzle where the player passes through matching color gates.",
        "objective": "Reach the final gate by choosing the correct color.",
        "controls": "Press R, G, or B to select a color.",
        "mechanic": "The player must match the current gate color.",
        "win": "Pass five gates correctly.",
        "lose": "Choose the wrong color.",
        "hazards": "Incorrect color gates.",
        "targets": "Matching color gates.",
    },
]

def generate_design():
    DESIGN_DIR.mkdir(parents=True, exist_ok=True)

    idea = random.choice(GAME_IDEAS)
    timestamp = datetime.now().isoformat(timespec="seconds")

    content = f"""# {idea["title"]}

Generated by MindCraft.

## Generation
- Generated at: {timestamp}

## 1. Game Identity

### Game Title
{idea["title"]}

### Short Description
{idea["description"]}

### Core Objective
{idea["objective"]}

## 2. Gameplay

### Player Controls
{idea["controls"]}

### Main Mechanic
{idea["mechanic"]}

### Win Condition
{idea["win"]}

### Lose Condition
{idea["lose"]}

## 3. World

### Player
A controllable player character.

### Enemies or Hazards
{idea["hazards"]}

### Collectibles or Targets
{idea["targets"]}

### Boundaries
The player must remain inside the playable game area.

## 4. Technical Requirements

- Browser playable
- HTML5 Canvas or DOM
- Vanilla JavaScript
- No external runtime dependencies
- Single self-contained HTML file

## 5. Playtest Requirements

The generated game must allow verification that:
- The game loads successfully
- Player input works
- The main mechanic works
- Collision or boundary logic works
- Win and lose conditions can be reached
- No uncaught JavaScript errors occur

## 6. Compliance

The final game must visibly contain:

**Powered by @Modiqo & #rote**
"""

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Generated: {OUTPUT}")
    print(f"Game: {idea['title']}")

if __name__ == "__main__":
    generate_design()
